apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-backend
  namespace: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-backend
  template:
    metadata:
      labels:
        app: app-backend
    spec:
      containers:
        - name: app-backend
          image: ghcr.io/ase-cx/url-shortener-backend:1.0.0
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              value: "mongodb://mongo-service.url-shortener.svc.cluster.local:27017"       

---
apiVersion: v1
kind: Service
metadata:
  name: app-backend-service
  namespace: url-shortener
spec:
  selector:
    app: app-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000