name: Docker build on release

on:
  push:
    tags:
      - '*.*.*'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get latest tag
        id: latest-tag
        run: |
          echo "::set-output name=tag::$(git describe --tags --abbrev=0)"
      

      - name: Set image tag
        id: image-tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "::set-output name=tag::${{ steps.latest-tag.outputs.tag }}"
          else
            echo "::set-output name=tag::${{ github.ref_name }}"
          fi
      
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/ase-cx/url-shortener-backend:${{ steps.image-tag.outputs.tag }}, ghcr.io/ase-cx/url-shortener:latest
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

